version: "3"

dotnev: [".env"]

tasks:
  config:
    cmds:
      - cmd: cmake -B build/desktop -S . -G Ninja -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DCMAKE_BUILD_TYPE=Debug
        platforms: [darwin, linux]
      - cmd: cmake -B build/desktop -S . -G Ninja -DCMAKE_EXPORT_COMPILE_COMMANDS=1
        platforms: [windows]
      #- cmake -E create_hardlink build/desktop/compile_commands.json build/compile_commands.json
  config-web:
    cmds:
      - cmake -B build/web -S . -G Ninja -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=$EMSDK/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake
      - cmake -E create_hardlink build/web/compile_commands.json build/compile_commands.json

  build-tests:
    cmds:
      - cmake --build build/desktop --target kaze_unit_tests
  run-tests:
    deps: [build-tests]
    cmds:
      - build/desktop/tests/unit_tests/kaze_unit_tests

  build-*:
    vars:
        TEST_NAME: "{{index .MATCH 0}}"
    cmds:
      - cmake --build build/desktop --target kaze_test_{{.TEST_NAME}}
  run-*:
    deps: ["build-{{index .MATCH 0}}"]
    vars:
        TEST_NAME: "{{index .MATCH 0}}"
    cmds:
      - cd build/desktop/tests/runtime && ./kaze_test_{{.TEST_NAME}}

  build-sandbox-web:
    cmds:
      - cmake --build build/web --target kaze_engine_sandbox
