set(KAZE_MODULE KAZE_NATIVE)

if (KAZE_PLATFORM_ANDROID)
    kaze_add_submodule(android)
elseif(KAZE_PLATFORM_EMSCRIPTEN)
    kaze_add_submodule(emscripten)
elseif(KAZE_PLATFORM_IOS)
    kaze_add_submodule(ios)
elseif(KAZE_PLATFORM_MACOS)
    kaze_add_submodule(macos)
endif()
