#pragma once
#include <kaze/core/lib.h>
#include <kaze/core/Action.h>
#include <kaze/core/AlignedAllocator.h>
#include <kaze/core/AlignedList.h>
#include <kaze/core/AssetLoader.h>
#include <kaze/core/CommandQueue.h>
#include <kaze/core/concepts.h>
#include <kaze/core/ConditionalAction.h>
#include <kaze/core/debug.h>
#include <kaze/core/endian.h>
#include <kaze/core/errors.h>
#include <kaze/core/Handle.h>
#include <kaze/core/ImageContainer.h>
#include <kaze/core/intrinsics.h>
#include <kaze/core/json.h>
#include <kaze/core/main.h>
#include <kaze/core/ManagedMem.h>
#include <kaze/core/memory.h>
#include <kaze/core/MemView.h>
#include <kaze/core/MultiPool.h>
#include <kaze/core/Pool.h>
#include <kaze/core/ServiceProvider.h>
#include <kaze/core/traits.h>
#include <kaze/core/Window.h>
#include <kaze/core/WindowConstants.h>

#include <kaze/core/filesys.hpp>
#include <kaze/core/input.hpp>
#include <kaze/core/io.hpp>
#include <kaze/core/macros/enum.h>
#include <kaze/core/math.hpp>
#include <kaze/core/platform/defines.h>
#include <kaze/core/platform/backend.hpp>
